# Generated by Django 4.2.5 on 2023-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='works')),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
